### ISSUE TITLE
DateTime not Defined in clean install

### ISSUE THREAD

**Issue by darth-pr** [trevorlewis/TEXT-Language-REST#2]
balrog:TEXT-Language-REST pramirez$ julia src/lidHttpServer.jl test/text.tsv
ERROR: DateTime not defined
 in include at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.12.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/pramirez/.julia/v0.3/Stage/src/Stage.jl, in expression starting on line 32
while loading /Users/pramirez/.julia/v0.3/Ollam/src/Ollam.jl, in expression starting on line 20
while loading /Users/pramirez/.julia/v0.3/Text/src/Text.jl, in expression starting on line 20
while loading /Users/pramirez/Desktop/Dry Run (Trevor)/TEXT-Language-REST/src/lidHttpServer.jl, in expression starting on line 25

**Comment by trevorlewis** [comment]
Fixed this issue by using Stage.jl for Julia v0.3 release.
