### ISSUE TITLE
Installation Procedure to Include Backward Compat with Prerequisites

### ISSUE THREAD

**Issue by darth-pr** [trevorlewis/TEXT-Language-REST#3]
if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
julia -e 'versioninfo(); Pkg.init();'
julia -e 'Pkg.clone("https://github.com/saltpork/Stage.jl"); cd(Pkg.dir("Stage")); run(`git checkout last-0.3-release`)'
julia -e 'Pkg.clone("https://github.com/mit-nlp/Ollam.jl");'
julia -e 'Pkg.clone("https://github.com/mit-nlp/Text.jl");'
julia -e 'Pkg.build();'

**Comment by trevorlewis** [comment]
Fixed this issue by creating install.sh to install the package with the prerequisite packages.
